server:
  port: 8006
spring:
  application:
    name: provider-ticket
  datasource:
    name: ebuy
    password: 123456
    url: jdbc:mysql://192.168.71.146:3306/wangchao_test
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP注册
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



