server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server #ereka实例的主机名
    # 心跳间隔
    #lease-renewal-interval-in-seconds: 3
    # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    #lease-expiration-duration-in-seconds: 7
  client:
    register-with-eureka: false # 不把自己注册到eureka上,集群时启用true
    fetch-registry: false # 不从eureka上来获取服务的注册信息
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    service-url:
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/  #注册地址
  server:
    enable-self-preservation: false  #关闭自我保护模式（默认为true）（缺省为启动，比如api提供者关闭了，但是eureka仍然会保留）
     # 设置清理间隔,单位为毫秒,默认为0
     # 清理间隔（毫秒，默认 60秒），将有问题的api提供者或app消费者剔除掉
    eviction-interval-timer-in-ms: 3000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 60000
spring:
  application:
    name: eureka-server  #eureka.server.enable-self-preservation