spring:
  application:
    name: provdier-server
  datasource:
    name: ebuy
    password: 123456
    url: jdbc:mysql://192.168.71.146:3306/zouhg_test
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8011
eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP注册
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: false  #打开hystrix在feign的开关